# Generated by Django 4.1.4 on 2023-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_ground',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
